### PR TITLE
Confirmation dialogs refactor, JS Cleanup, and Fixed Reviews for when User Deleted

### LINKED ISSUE #379: No confirmation dialog on environment deletion

### PR DESCRIPTION
**Pull request by manfromjupyter**
- Adding streamlined accessibility-supporting, streamlined confirmation dialog for Environments, Notebook deletions, Users, and Site Warnings. Did not add for Change Requests or groups because you can't delete them, and did not add for group landing page because it doesn't actually delete anything, simply remove from view, and did not apply to stages and reviews because they are admin only and not already in the JS (would have to completely remake in JS like I did the Users just to get them to work the same). Did not apply new confirmation dialog to deletion of deprecation banner either, but thinking we might want that... Can do in another ticket? Felt like this one was getting too large
- Did tech debt cleanup for the two main JS files and something that's been bothering me for a while. Did not change any of that code, merely moved it to respective sections they should belong and fixed spacing where it was wrong. Deleted only like 3-4 lines but that was code that no longer existed.
- Fixed reviews for when a user is deleted. (Can move this to another ticket if we really want it.. 100% of the the fix is on the /_reviews.slim page below). Only did it because I was starting to do the confirmation dialog for reviews deletions.

Closes #379, #380, #381, and #406

Here are the dialogs. Let me know if the User deletion one is too verbose
site-warning-confirmation-dialog-final
environments-confirmation-dialog-final
user-delete-confirmation-dialog-final
notebook-delete-confirmation-dialog-final

### CODE REVIEW

**Comment by mcrutch** [comment]
Reading this one breaks my brain:
image
Also, either "the user's" or "their" "All of user's" sounds like you accidentally a word.

Maybe find a way to condense it.
- All notebooks, groups (and associated notebooks), pending change requests, comments and notebook metrics owned by this user will be deleted
- Any notebook deprecated by this user will now say it was deprecated by "Unknown"
- Any revisions .,.blah blah blah

**Comment by manfromjupyter** [comment]
> Reading this one breaks my brain:
> image
> Also, either "the user's" or "their" "All of user's" sounds like you accidentally a word.
> 
> Maybe find a way to condense it.
> 
> * All notebooks, groups (and associated notebooks), pending change requests, comments and notebook metrics owned by this user will be deleted
> * Any notebook deprecated by this user will now say it was deprecated by "Unknown"
> * Any revisions .,.blah blah blah

@mcrutch, Ah gotcha. Think I used "All" just to scare people. All can be a lot. Will make this change and make it tighter in wording and get back to you

**Comment by mcrutch** [comment]
Problem wasn't the "All" it was the "All of user's" vs "All of the user's" or "All of their..."  "All of user's" sounds like you forgot a word

**Comment by manfromjupyter** [comment]
@mcrutch How do you feel about this?

better user deletion confirmation

**Comment by mcrutch** [comment]
@manfromjupyter can you resolve conflicts on this one, and I will pull the trigger on it

**Comment by manfromjupyter** [comment]
@mcrutch Just was a comment that was added in this branch but wasn't added to main. Good to go 👍

**Pull request merged**
