### PR TITLE
Exclude clicks on deprecated notebooks when picking those for review

### LINKED ISSUE #408: Make it so automated nominations of reviews don't occur for deprecated notebooks
Have the automated nomination nightly_computation ignoe deprecated notebooks.

### PR DESCRIPTION
**Pull request by mcrutch**
Closes #408

### CODE REVIEW

**Comment by manfromjupyter** [comment]
@mcrutch So I deprecated a few popular notebooks and then ran `bundle exec rails runner script/run_job.rb nightly_computation` and your code did work. Those ones did not get chosen but for whatever reason, the Reviews page now looks like this. It's almost like the reviews didn't properly do the check for ones that are already in progress and skip them. I can research into it tomorrow. Might have been due to database changes since my commit messages one too... Idk.

reviews after nightly computation

**Comment by mcrutch** [comment]
Those extra rows are for the "Compliance" review which I turned on during the test, so the Notebook Reviews table doesn't handle those correctly.

**Comment by manfromjupyter** [comment]
@mcrutch Then this is good to go on my end then, unless you wanted me or you to get it working for compliance reviews and then submit just to make sure

**Comment by mcrutch** [comment]
I made that it's own ticket #439. That problem exists with or without this pull request.

**Pull request merged**
