### PR TITLE
Make the usage of "tag" less ambiguous throughout the code

### LINKED ISSUE #463: Fix ambiguity of the variable name "tag" through the code
Sometimes tag is used to store a tag object
Sometimes tag is used to store the tag text
Both uses are often found in the same file (see daily_subscription_email_text.slim as an example)

Tracing bugs involving tags is very difficult because of this and it has caused problems when doing a copy/paste between views in the past.

### PR DESCRIPTION
**Pull request by mcrutch**
Prepare codebase for normalization of the tag field Closes #463
Related to #360

### CODE REVIEW

**Comment by manfromjupyter** [comment]
Still testing this but did we also want to rename "tag" in the SQL table? 

tag in table

**Comment by mcrutch** [comment]
Longer term, that is going away so didn't touch it.

**Comment by manfromjupyter** [comment]
Okie doke. Only other problem is that `/tags` page doesn't render due to an error. I will fix this though

tags page error

**Comment by mcrutch** [comment]
since that is an S and assuming that is the only issue, I am going to guess I was trying to hit Ctrl+S with the character highlighted at some point and didn't retest that page, because I had that page working

**Review by manfromjupyter — APPROVED** [review]
Wow that took me slightly too long to figure out even after you saying "S" was the issue hahaha. Confirmed that was all that was needed and everything else looks good. Search worked for tag filtering also but maybe I also want to flag that after doing it twice no searches at all work. Maybe just a SOLR issue?

**Pull request merged**
